"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_orange)\
$os\
$username\
[](bg:color_yellow fg:color_orange)\
$git_branch\
$git_status\
[](fg:color_yellow bg:color_blue)\
$directory\
[ ](fg:color_blue)"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[os]
disabled = false 
style = "bg:color_orange fg:color_fg0"

[os.symbols]
Fedora = "󱓟"
Linux = " 󰣛 󱝆 󱓂 l "

[username]
show_always = true
style_user = "bg:color_orange fg:color_fg0"
style_root = "bg:color_orange fg:color_fg0"
#format = '[ $user]($style)'
format = '[ robert ]($style)'

[directory]
style = "fg:color_fg0 bg:color_blue"
format = "[ $path ]($style)"
truncation_length = 6
truncate_to_repo = false  # Set to true to prevent truncation within a repo
truncation_symbol = "…/"

[directory.substitutions]
#"Documents" = "󰈙 "
#"Downloads" = " "
#"Music" = "󰝚 "
#"Pictures" = " "
#"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_yellow"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_yellow)]($style)'

[git_status]
style = "bg:color_yellow"
format = '[[($all_status$ahead_behind)](fg:color_fg0 bg:color_yellow)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[$time](fg:color_fg0 bg:color_bg1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
